version: 'v.2.9.0'
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/apps
      - /app/node_modules
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0"